name: CI

on: [push]

env:
  SERVER_DIRECTORY: server

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install server dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run unit tests
        run: npm run test:unit
        working-directory: ${{ env.WORKING_DIRECTORY }}

      # - name: Setup Docker
      #   uses: docker-practice/actions-setup-docker@master

      # - name: Docker Compose up
      #   run: docker-compose up -d

      # - name: Run integration tests
      #   run: npm run test:integration
