name: CI

on: [push]

env:
  SERVER_DIRECTORY: server

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: a7b231eb-f86d-486d-b669-d1e9d747dc62
      SERVER_PORT: 8080
      SOCKET_PORT: 8081
      MONGO_URI: mongodb://localhost:27017/?directConnection=true
      PEPER: thisIsPeper
      GMAIL_USER: dolphin.club.system@gmail.com
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master

      - name: Docker compose
        run: docker-compose up -d

      # - name: Check server
      #   run: |
      #     until $(curl --output /dev/null --silent --head --fail http://localhost:8080/test); do
      #       echo "Waiting for server..."
      #       sleep 5
      #     done

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install server dependencies
        run: npm ci
        working-directory: ${{ env.SERVER_DIRECTORY }}

      - name: Run unit tests
        run: npm run test:unit
        working-directory: ${{ env.SERVER_DIRECTORY }}

      - name: Run integration tests
        run: npm run test:integration
        working-directory: ${{ env.SERVER_DIRECTORY }}
