name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Docker Compose up
        run: docker-compose up -d

    # - name: Run integration tests
    #   run: npm run test:integration
